<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
        <OutputType>Library</OutputType>
        <PackageId>Lmc.Fable.Profiler</PackageId>
        <Version>2.2.0</Version>
        <PackageProjectUrl>https://bitbucket.lmc.cz/projects/ARCHI/repos/fable-profiler/browse</PackageProjectUrl>
        <RepositoryUrl>https://bitbucket.lmc.cz/projects/ARCHI/repos/fable-profiler/browse</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="AssemblyInfo.fs" />
    </ItemGroup>
    
    <ItemGroup>
        <Compile Include="Model.fs" />
        <Compile Include="Profiler.fs" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="*.fsproj; *.fs; *.scss;" PackagePath="fable\" />
    </ItemGroup>

    <Import Project="..\..\.paket\Paket.Restore.targets" />

</Project>